### ISSUE TITLE
Doing Watson AI on laptop

### ISSUE THREAD

**Issue by namgk** [johnwalicki/Node-RED-Tello-Control#11]
Hi there,

I just want to clarify about this tutorial and all the Tello connectivity related.

It won't work with Watson if your laptop does not have an Ethernet (wired) Internet connection right?

Because when you're connected to the drone via the laptop's Wi-Fi to send command, you won't have any other Internet connection to talk to Watson?

Thanks

**Comment by johnwalicki** [comment]
Hi @namgk  - Correct - you need a wired Ethernet connection to the Internet to send the photos for Watson Visual Recognition image classification.  The WiFi is connected to the Tello drone hotspot.
