### ISSUE TITLE
Tello does not give back telemetry data via UDP 8890

### ISSUE THREAD

**Issue by AThobaben** [johnwalicki/Node-RED-Tello-Control#14]
Hi John
first of all thanks for this great tutorial :-)
I was able to fly the drone by the flow/control buttons on the dashboard.
Unfortunately I don't receive data back from the drone.

Commands are transfered and I receive the "OK" back - so basic coversation works on Windows 10 and Mac OS-X. On both machines I switched of firewall and checked with TCPView or netstat for a listening software at UDP 8890 towards 192.168.10.1 - but could not find anything listening.

Any Idea? 

I did not check with linux yet because I wanted to use it under Windows and I am pretty sure, that ports are open.

Best Regards,
Axel

**Comment by VipinNa** [comment]
I am getting the same issue, any views, please advise,

Below is the node-red trace shows some error,

:08 - [info] [udp in:890bfeab.dba5] udp: port 52955 already in use
10 Sep 17:55:08 - [info] Started flows
10 Sep 17:55:08 - [info] [udp in:b588c26f.cc38e] udp listener at 0.0.0.0:52955
10 Sep 17:55:08 - [info] [udp in:890bfeab.dba5] udp listener at 0.0.0.0:52955
**10 Sep 17:55:08 - [error] [udp in:bd7e5975.45fad8] error: EACCES**
10 Sep 17:55:08 - [info] Server now running at http://127.0.0.1:1880/
10 Sep 17:55:08 - [info] [udp out:9d63d734.6c6db] udp re-use socket: 52955 -> 192.168.10.1:8889
10 Sep 17:55:08 - [info] [udp out:50a17ab9.0520a4] udp re-use socket: 52955 -> 192.168.10.1:8889

**Comment by johnwalicki** [comment]
@VipinNa  - Are you certain you have opened the UDP ports in your firewall?
See the Linux / MAC OSX instructions on this page:
https://github.com/johnwalicki/Node-RED-Tello-Control/blob/main/docs/PART5.md

**Comment by VipinNa** [comment]
Yes, I am using Windows 10. 
See firewall settings & UDP status on CLI
<img width="796" alt="FirewallSettings" src="https://user-images.githubusercontent.com/90443036/132994229-3aa94049-d6c7-49da-a58b-5c14ff1107c0.png">
<img width="424" alt="cmd_UDP Port" src="https://user-images.githubusercontent.com/90443036/132994231-cc029ecd-826f-4ac4-adcc-da37dea4143d.png">

**Comment by VipinNa** [comment]
hi @johnwalicki,

I check also on wireshark, i am getting data from drone but a i can't still see any data on node-red.
Attached is the screen shot.
<img width="927" alt="DroneDataWireshark" src="https://user-images.githubusercontent.com/90443036/133368875-eebeeeed-7d03-4aa2-9cb7-3ba3bf88b1e1.png">

**Comment by VipinNa** [comment]
Hi @johnwalicki,,
The issue is resolved.
I installed Ubuntu 20.04 and then opened the ports.

Now it is working fine.

Thank you for you time.

**Comment by johnwalicki** [comment]
Good news.  I have no experience with Windows firewall configuration. Glad you were able to set up Ubuntu.
