### ISSUE TITLE
Tello nodes for node red

### ISSUE THREAD

**Issue by sreyamsjain** [johnwalicki/Node-RED-Tello-Control#15]
How do I get the various Tello nodes in node red? Is there a npm install for the same?

Thanks

**Comment by johnwalicki** [comment]
Hi - There are no tello nodes available but you can import the flows from this repo to control your drone.

**Comment by sreyamsjain** [comment]
Hi, bu tin your part6 flow diagram, there are some nodes that are Tello. Am I reading it wrong?

**Comment by johnwalicki** [comment]
In Part 6, the instructions teach you how to create Subflows for various Tello movements.  They aren't actually Node-RED nodes, just snippets of Node-RED flows that are in separate tabs that become reusable.
