### ISSUE TITLE
Type of drone

### ISSUE THREAD

**Issue by Eiman41** [johnwalicki/Node-RED-Tello-Control#17]
Can you please give me the exact name and description of the drone so I don't purchase the wrong type?
the drone is mentioned here 
https://developer.ibm.com/tutorials/program-ryze-dji-tello-drone-using-sdks-and-node-red/#1-send-commands-to-the-drone-using-node-red-and-the-dji-apis

**Comment by johnwalicki** [comment]
The Rzye Tello or the Rzye Tello EDU are excellent educational programming drones.
