### ISSUE TITLE
node red installation

### ISSUE THREAD

**Issue by axdonlee** [johnwalicki/Node-RED-Tello-Control#18]
Hi,

i tried to install node-red and was successful but when i wanted to install dashboard, i got 2 error stated: npm WARN lee@1.0.0 no desription and npm WARN lee@1.0.0 no repository field. i did a check for the error, it need to update the version but i was unable to update.Please help

**Comment by johnwalicki** [comment]
Did you try:
$ cd .node-red
$ npm install node-red-dashboard

**Comment by axdonlee** [comment]
Good day

It is good to hear from you. I had installed both of the item you mentioned. There was two error and I can’t see the photo icon Nor video streaming.

I wonder what I can do next. Maybe I can set a time where u can remotely control my laptop to fix for me? I tried to figure a whole day but still unsuccessful. 

This node red is indeed good to use. Anyway can u show me if I want to create a Mission how do I do it. Where can I learn to create node? 

I wanted to create video streaming and photo taking while manually control tello. Next I want to set a preplanned flight path for tello to execute. 

I hope you can help me as I probably doing it as a school project. If there is charges , please let me know.

Thanks

Regards
Don 
+65 93280288

**Comment by axdonlee** [comment]
Good day

I would like to check whether do ur program include photo taking and video streaming function? 

Any different procedure if I install on MAC book? I appreciate your help. Thanks

**Comment by axdonlee** [comment]
After going through the tutorial, my dashboard still does not have the option on tello camera and video streaming. How to I installed those function? Are u able to assist me. Thanks

**Comment by johnwalicki** [comment]
@axdonlee Did you get Node-RED and the node-red-dashboard Nodes installed?  Asking if I can close this ticket.

**Comment by axdonlee** [comment]
Hi

Done.
