### ISSUE TITLE
how to use face detection 

### ISSUE THREAD

**Issue by theman162** [johnwalicki/Node-RED-Tello-Control#20]
hi i tried to use face detection but was unable to.Is there any solutions for these?

**Comment by johnwalicki** [comment]
Watson Visual Recognition has sunset the Face Detection identification service.
You might be interested in Jabrils' Tello project:
https://developer.ibm.com/videos/jabrils-tackles-the-ibm-developer-drone-challenge-pt-2/
https://github.com/Jabrils/TelloTV
