### ISSUE TITLE
How to Store Videos/Images Recorded/Captured by Drone in PC thru Node-RED?

### ISSUE THREAD

**Issue by muditkhare10** [johnwalicki/Node-RED-Tello-Control#22]
Hi John,

Firstly I want to give you big thanks for Node-RED and Tello Drone implementation in such a easy and interesting way.

It would be great if you can suggest me how can I store drone Recorded/Captured videos/images in my laptop?

Please find some screen shots of Video streaming image by Drone.

**Thanks & Regards,
Mudit Khare**

<img width="960" alt="Tello__Drone_Video_Stream" src="https://user-images.githubusercontent.com/10301886/71757273-6fa37700-2eba-11ea-81c6-dd43e5b45f4a.png">
<img width="301" alt="Tello_Drone_Video_Stream__1" src="https://user-images.githubusercontent.com/10301886/71757410-b0e85680-2ebb-11ea-84f8-1df2634117e1.png">

**Comment by johnwalicki** [comment]
You can easily use the Node-RED file node to save the image to your local laptop. Send the image in msg.payload and set the msg.filename to the local file you want to save as.

If you want to write the images to IBM Cloud Object Storage, there are nodes for that too.  I have not figured out how to configure the node-red-contrib-cos nodes however.

**Comment by muditkhare10** [comment]
Hi John,

Now I am able to save Drone captured images to IBM Cloud Object Storage via using cos-put node  Cloud Object Storage  in my local Node-RED.

Thanks for your suggestion.
