### ISSUE TITLE
not getting info back

### ISSUE THREAD

**Issue by andyuk5** [johnwalicki/Node-RED-Tello-Control#7]
Hi Great tutorial but I can not get information back from the Tello.
I have turned off my virus and fire wall but still not getting anything back.
am I missing something.

**Comment by johnwalicki** [comment]
Hi Andy - Windows, Linux or Mac? There are a few firewall port rules that need to be configured.

**Comment by andyuk5** [comment]
Hi john

Sorry should have said, win 10
And antivirus and firewalls all off.

Regards

Andy

On 27 Apr 2019 7:38 p.m., John Walicki <notifications@github.com> wrote:

Hi Andy - Windows, Linux or Mac? There are a few firewall port rules that need to be configured.

**Comment by andyuk5** [comment]
Hi John

Sorry have you had chance to look in to this or should I try it on a windows 7 machine I have.

Andyuk5

**Comment by andyuk5** [comment]
Hi John

Works great with a raspberry pi 3
Will try video next.
Thank you for this.

Regards

Andyuk5

**Comment by johnwalicki** [comment]
Fantastic news - I'm a Linux expert - switched to a Linux Desktop 20+ years ago from OS/2. I ran WinNT for about a week I think .  Occasionally run Mac OS X.  Have never run Windows so I can't say much about firewall rules on Windows.  I'm going to close this ticket.
