### ISSUE TITLE
I don't see any information in the dashboard

### ISSUE THREAD

**Issue by thomassuedbroecker** [johnwalicki/Node-RED-Tello-Control#9]
I can start the drone and give commands using Node-RED that means: starting, landing and turn works, but I can not see any information inside the dashboard of Stats, Accel or Movement. What I am doing wrong?

Mac OS 10.14.5
Chrome: Version 74.0.3729.169 (Official Build) (64-bit)

Here is the output of the Node log for the Node-RED instance:

`Welcome to Node-RED
===================

21 Jun 15:54:25 - [info] Node-RED version: v0.20.6
21 Jun 15:54:25 - [info] Node.js  version: v8.14.0
21 Jun 15:54:25 - [info] Darwin 18.6.0 x64 LE
21 Jun 15:54:25 - [info] Loading palette nodes
21 Jun 15:54:25 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
21 Jun 15:54:26 - [info] Dashboard version 2.15.4 started at /ui
21 Jun 15:54:26 - [info] Settings file  : /Users/thomassuedbroecker/.node-red/settings.js
21 Jun 15:54:26 - [info] Context store  : 'default' [module=memory]
21 Jun 15:54:26 - [info] User directory : /Users/thomassuedbroecker/.node-red
21 Jun 15:54:26 - [warn] Projects disabled : editorTheme.projects.enabled=false
21 Jun 15:54:26 - [info] Flows file     : /Users/thomassuedbroecker/.node-red/flows_Thomass-MBP-3.fritz.box.json
21 Jun 15:54:26 - [info] Creating new flow file
21 Jun 15:54:26 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

21 Jun 15:54:26 - [info] Starting flows
21 Jun 15:54:26 - [info] Started flows
21 Jun 15:54:26 - [info] Server now running at http://127.0.0.1:1880/
21 Jun 15:57:04 - [info] Stopping flows
21 Jun 15:57:04 - [info] Stopped flows
21 Jun 15:57:04 - [info] Starting flows
21 Jun 15:57:04 - [info] Started flows
21 Jun 15:57:04 - [info] [udp in:e8fa8d62.5ba14] udp listener at 0.0.0.0:52955
21 Jun 15:57:04 - [info] [udp out:eaec231.1a027e] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:05:23 - [info] Stopping flows
21 Jun 16:05:23 - [info] [udp out:eaec231.1a027e] udp output stopped
21 Jun 16:05:23 - [info] Stopped flows
21 Jun 16:05:23 - [info] Starting flows
21 Jun 16:05:23 - [info] [udp in:f0a7b791.8fbdd8] udp: port 52955 already in use
21 Jun 16:05:23 - [info] Started flows
21 Jun 16:05:23 - [info] [udp in:e8fa8d62.5ba14] udp listener at 0.0.0.0:52955
21 Jun 16:05:23 - [info] [udp in:f0a7b791.8fbdd8] udp listener at 0.0.0.0:52955
21 Jun 16:05:23 - [info] [udp out:eaec231.1a027e] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:05:23 - [info] [udp out:bc7c5bb9.f7ae08] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:06:13 - [info] Stopping flows
21 Jun 16:06:13 - [info] [udp out:eaec231.1a027e] udp output stopped
21 Jun 16:06:13 - [info] Stopped flows
21 Jun 16:06:13 - [info] Starting flows
21 Jun 16:06:13 - [info] [udp in:f0a7b791.8fbdd8] udp: port 52955 already in use
21 Jun 16:06:13 - [info] [udp in:bc6a5c5a.dc92b] udp: port 52955 already in use
21 Jun 16:06:13 - [info] Started flows
21 Jun 16:06:13 - [info] [udp in:e8fa8d62.5ba14] udp listener at 0.0.0.0:52955
21 Jun 16:06:13 - [info] [udp in:f0a7b791.8fbdd8] udp listener at 0.0.0.0:52955
21 Jun 16:06:13 - [info] [udp in:bc6a5c5a.dc92b] udp listener at 0.0.0.0:52955
21 Jun 16:06:13 - [info] [udp out:eaec231.1a027e] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:06:13 - [info] [udp out:bc7c5bb9.f7ae08] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:06:13 - [info] [udp out:ed91acb.4b6765] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:08:54 - [info] Stopping flows
21 Jun 16:08:54 - [info] [udp out:eaec231.1a027e] udp output stopped
21 Jun 16:08:54 - [info] Stopped flows
21 Jun 16:08:54 - [info] Starting flows
21 Jun 16:08:54 - [info] [udp in:f0a7b791.8fbdd8] udp: port 52955 already in use
21 Jun 16:08:54 - [info] [udp in:bc6a5c5a.dc92b] udp: port 52955 already in use
21 Jun 16:08:54 - [info] [udp in:6d0293d0.7830fc] udp: port 52955 already in use
21 Jun 16:08:54 - [info] Started flows
21 Jun 16:08:54 - [info] [udp in:e8fa8d62.5ba14] udp listener at 0.0.0.0:52955
21 Jun 16:08:54 - [info] [udp in:f0a7b791.8fbdd8] udp listener at 0.0.0.0:52955
21 Jun 16:08:54 - [info] [udp in:bc6a5c5a.dc92b] udp listener at 0.0.0.0:52955
21 Jun 16:08:54 - [info] [udp in:6d0293d0.7830fc] udp listener at 0.0.0.0:52955
21 Jun 16:08:54 - [info] [udp in:610c4dfa.510b74] udp listener at 0.0.0.0:8890
21 Jun 16:08:54 - [info] [udp out:eaec231.1a027e] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:08:54 - [info] [udp out:bc7c5bb9.f7ae08] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:08:54 - [info] [udp out:ed91acb.4b6765] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:08:54 - [info] [udp out:bdd1e889.8e4d98] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:11:36 - [info] Stopping flows
21 Jun 16:11:36 - [info] [udp out:eaec231.1a027e] udp output stopped
21 Jun 16:11:36 - [info] [udp in:610c4dfa.510b74] udp listener stopped
21 Jun 16:11:36 - [info] Stopped flows
21 Jun 16:11:36 - [info] Starting flows
21 Jun 16:11:36 - [info] [udp in:f0a7b791.8fbdd8] udp: port 52955 already in use
21 Jun 16:11:36 - [info] [udp in:bc6a5c5a.dc92b] udp: port 52955 already in use
21 Jun 16:11:36 - [info] [udp in:6d0293d0.7830fc] udp: port 52955 already in use
21 Jun 16:11:36 - [info] [udp in:a4572688.a2c728] udp: port 52955 already in use
21 Jun 16:11:36 - [info] [udp in:a0193be4.e9f708] udp: port 8890 already in use
21 Jun 16:11:36 - [info] Started flows
21 Jun 16:11:36 - [info] [udp in:e8fa8d62.5ba14] udp listener at 0.0.0.0:52955
21 Jun 16:11:36 - [info] [udp in:f0a7b791.8fbdd8] udp listener at 0.0.0.0:52955
21 Jun 16:11:36 - [info] [udp in:bc6a5c5a.dc92b] udp listener at 0.0.0.0:52955
21 Jun 16:11:36 - [info] [udp in:6d0293d0.7830fc] udp listener at 0.0.0.0:52955
21 Jun 16:11:36 - [info] [udp in:a4572688.a2c728] udp listener at 0.0.0.0:52955
21 Jun 16:11:36 - [info] [udp in:610c4dfa.510b74] udp listener at 0.0.0.0:8890
21 Jun 16:11:36 - [info] [udp in:a0193be4.e9f708] udp listener at 0.0.0.0:8890
21 Jun 16:11:36 - [info] [udp out:eaec231.1a027e] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:11:36 - [info] [udp out:bc7c5bb9.f7ae08] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:11:36 - [info] [udp out:ed91acb.4b6765] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:11:36 - [info] [udp out:bdd1e889.8e4d98] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:11:36 - [info] [udp out:5a993ab9.2a1764] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:13:03 - [info] Stopping flows
21 Jun 16:13:03 - [info] [udp out:eaec231.1a027e] udp output stopped
21 Jun 16:13:03 - [info] [udp in:610c4dfa.510b74] udp listener stopped
21 Jun 16:13:03 - [info] Stopped flows
21 Jun 16:13:03 - [info] Starting flows
21 Jun 16:13:03 - [info] [udp in:f0a7b791.8fbdd8] udp: port 52955 already in use
21 Jun 16:13:03 - [info] [udp in:bc6a5c5a.dc92b] udp: port 52955 already in use
21 Jun 16:13:03 - [info] [udp in:6d0293d0.7830fc] udp: port 52955 already in use
21 Jun 16:13:03 - [info] [udp in:510246f1.e52d88] udp: port 52955 already in use
21 Jun 16:13:03 - [info] [udp in:8b04569b.24a2c8] udp: port 8890 already in use
21 Jun 16:13:03 - [info] Started flows
21 Jun 16:13:03 - [info] [udp in:e8fa8d62.5ba14] udp listener at 0.0.0.0:52955
21 Jun 16:13:03 - [info] [udp in:f0a7b791.8fbdd8] udp listener at 0.0.0.0:52955
21 Jun 16:13:03 - [info] [udp in:bc6a5c5a.dc92b] udp listener at 0.0.0.0:52955
21 Jun 16:13:03 - [info] [udp in:6d0293d0.7830fc] udp listener at 0.0.0.0:52955
21 Jun 16:13:03 - [info] [udp in:510246f1.e52d88] udp listener at 0.0.0.0:52955
21 Jun 16:13:03 - [info] [udp in:610c4dfa.510b74] udp listener at 0.0.0.0:8890
21 Jun 16:13:03 - [info] [udp in:8b04569b.24a2c8] udp listener at 0.0.0.0:8890
21 Jun 16:13:03 - [info] [udp out:eaec231.1a027e] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:13:03 - [info] [udp out:bc7c5bb9.f7ae08] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:13:03 - [info] [udp out:ed91acb.4b6765] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:13:03 - [info] [udp out:bdd1e889.8e4d98] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:13:03 - [info] [udp out:327c07ef.f86218] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:20:18 - [info] Stopping flows
21 Jun 16:20:18 - [info] [udp out:eaec231.1a027e] udp output stopped
21 Jun 16:20:18 - [info] [udp in:610c4dfa.510b74] udp listener stopped
21 Jun 16:20:18 - [info] Stopped flows
21 Jun 16:20:18 - [info] Starting flows
21 Jun 16:20:18 - [info] [udp in:f0a7b791.8fbdd8] udp: port 52955 already in use
21 Jun 16:20:18 - [info] [udp in:bc6a5c5a.dc92b] udp: port 52955 already in use
21 Jun 16:20:18 - [info] [udp in:6d0293d0.7830fc] udp: port 52955 already in use
21 Jun 16:20:18 - [info] [udp in:f8512254.2873c] udp: port 52955 already in use
21 Jun 16:20:18 - [info] [udp in:ac5c6d3b.5f8d3] udp: port 8890 already in use
21 Jun 16:20:18 - [info] [udp in:91649fa.603c66] udp: port 52955 already in use
21 Jun 16:20:18 - [info] Started flows
21 Jun 16:20:18 - [info] [udp in:e8fa8d62.5ba14] udp listener at 0.0.0.0:52955
21 Jun 16:20:18 - [info] [udp in:f0a7b791.8fbdd8] udp listener at 0.0.0.0:52955
21 Jun 16:20:18 - [info] [udp in:bc6a5c5a.dc92b] udp listener at 0.0.0.0:52955
21 Jun 16:20:18 - [info] [udp in:6d0293d0.7830fc] udp listener at 0.0.0.0:52955
21 Jun 16:20:18 - [info] [udp in:f8512254.2873c] udp listener at 0.0.0.0:52955
21 Jun 16:20:18 - [info] [udp in:91649fa.603c66] udp listener at 0.0.0.0:52955
21 Jun 16:20:18 - [info] [udp in:610c4dfa.510b74] udp listener at 0.0.0.0:8890
21 Jun 16:20:18 - [info] [udp in:ac5c6d3b.5f8d3] udp listener at 0.0.0.0:8890
21 Jun 16:20:18 - [info] [udp out:eaec231.1a027e] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:20:18 - [info] [udp out:bc7c5bb9.f7ae08] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:20:18 - [info] [udp out:ed91acb.4b6765] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:20:18 - [info] [udp out:bdd1e889.8e4d98] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:20:18 - [info] [udp out:327c07ef.f86218] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:20:18 - [info] [udp out:44d94dbd.d7c874] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:11 - [info] Stopping flows
21 Jun 16:21:11 - [info] [udp out:eaec231.1a027e] udp output stopped
21 Jun 16:21:11 - [info] [udp in:610c4dfa.510b74] udp listener stopped
21 Jun 16:21:11 - [info] Stopped flows
21 Jun 16:21:11 - [info] Starting flows
21 Jun 16:21:11 - [info] [udp in:f0a7b791.8fbdd8] udp: port 52955 already in use
21 Jun 16:21:11 - [info] [udp in:bc6a5c5a.dc92b] udp: port 52955 already in use
21 Jun 16:21:11 - [info] [udp in:6d0293d0.7830fc] udp: port 52955 already in use
21 Jun 16:21:11 - [info] [udp in:99c591bd.1f0ac] udp: port 52955 already in use
21 Jun 16:21:11 - [info] [udp in:7728ffcb.04117] udp: port 8890 already in use
21 Jun 16:21:11 - [info] [udp in:91649fa.603c66] udp: port 52955 already in use
21 Jun 16:21:11 - [info] [udp in:679f0974.f22048] udp: port 52955 already in use
21 Jun 16:21:11 - [info] Started flows
21 Jun 16:21:11 - [info] [udp in:e8fa8d62.5ba14] udp listener at 0.0.0.0:52955
21 Jun 16:21:11 - [info] [udp in:f0a7b791.8fbdd8] udp listener at 0.0.0.0:52955
21 Jun 16:21:11 - [info] [udp in:bc6a5c5a.dc92b] udp listener at 0.0.0.0:52955
21 Jun 16:21:11 - [info] [udp in:6d0293d0.7830fc] udp listener at 0.0.0.0:52955
21 Jun 16:21:11 - [info] [udp in:99c591bd.1f0ac] udp listener at 0.0.0.0:52955
21 Jun 16:21:11 - [info] [udp in:91649fa.603c66] udp listener at 0.0.0.0:52955
21 Jun 16:21:11 - [info] [udp in:679f0974.f22048] udp listener at 0.0.0.0:52955
21 Jun 16:21:11 - [info] [udp in:610c4dfa.510b74] udp listener at 0.0.0.0:8890
21 Jun 16:21:11 - [info] [udp in:7728ffcb.04117] udp listener at 0.0.0.0:8890
21 Jun 16:21:11 - [info] [udp out:eaec231.1a027e] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:11 - [info] [udp out:bc7c5bb9.f7ae08] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:11 - [info] [udp out:ed91acb.4b6765] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:11 - [info] [udp out:bdd1e889.8e4d98] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:11 - [info] [udp out:327c07ef.f86218] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:11 - [info] [udp out:44d94dbd.d7c874] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:11 - [info] [udp out:d256ff94.22cd1] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:57 - [info] Stopping flows
21 Jun 16:21:57 - [info] [udp out:eaec231.1a027e] udp output stopped
21 Jun 16:21:57 - [info] [udp in:610c4dfa.510b74] udp listener stopped
21 Jun 16:21:57 - [info] Stopped flows
21 Jun 16:21:57 - [info] Starting flows
21 Jun 16:21:57 - [info] [udp in:f0a7b791.8fbdd8] udp: port 52955 already in use
21 Jun 16:21:57 - [info] [udp in:bc6a5c5a.dc92b] udp: port 52955 already in use
21 Jun 16:21:57 - [info] [udp in:6d0293d0.7830fc] udp: port 52955 already in use
21 Jun 16:21:57 - [info] [udp in:a4d98e09.1299d] udp: port 52955 already in use
21 Jun 16:21:57 - [info] [udp in:23ad3213.d4df8e] udp: port 8890 already in use
21 Jun 16:21:57 - [info] [udp in:91649fa.603c66] udp: port 52955 already in use
21 Jun 16:21:57 - [info] [udp in:679f0974.f22048] udp: port 52955 already in use
21 Jun 16:21:57 - [info] [udp in:834ea885.7a8108] udp: port 52955 already in use
21 Jun 16:21:57 - [info] Started flows
21 Jun 16:21:57 - [info] [udp in:e8fa8d62.5ba14] udp listener at 0.0.0.0:52955
21 Jun 16:21:57 - [info] [udp in:f0a7b791.8fbdd8] udp listener at 0.0.0.0:52955
21 Jun 16:21:57 - [info] [udp in:bc6a5c5a.dc92b] udp listener at 0.0.0.0:52955
21 Jun 16:21:57 - [info] [udp in:6d0293d0.7830fc] udp listener at 0.0.0.0:52955
21 Jun 16:21:57 - [info] [udp in:a4d98e09.1299d] udp listener at 0.0.0.0:52955
21 Jun 16:21:57 - [info] [udp in:91649fa.603c66] udp listener at 0.0.0.0:52955
21 Jun 16:21:57 - [info] [udp in:679f0974.f22048] udp listener at 0.0.0.0:52955
21 Jun 16:21:57 - [info] [udp in:834ea885.7a8108] udp listener at 0.0.0.0:52955
21 Jun 16:21:57 - [info] [udp in:610c4dfa.510b74] udp listener at 0.0.0.0:8890
21 Jun 16:21:57 - [info] [udp in:23ad3213.d4df8e] udp listener at 0.0.0.0:8890
21 Jun 16:21:57 - [info] [udp out:eaec231.1a027e] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:57 - [info] [udp out:bc7c5bb9.f7ae08] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:57 - [info] [udp out:ed91acb.4b6765] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:57 - [info] [udp out:bdd1e889.8e4d98] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:57 - [info] [udp out:327c07ef.f86218] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:57 - [info] [udp out:44d94dbd.d7c874] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:57 - [info] [udp out:d256ff94.22cd1] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:21:57 - [info] [udp out:9297f027.bc6b] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:29:16 - [info] Stopping flows
21 Jun 16:29:16 - [info] [udp out:eaec231.1a027e] udp output stopped
21 Jun 16:29:16 - [info] [udp in:610c4dfa.510b74] udp listener stopped
21 Jun 16:29:16 - [info] Stopped flows
21 Jun 16:29:16 - [info] Starting flows
21 Jun 16:29:16 - [info] [udp in:f0a7b791.8fbdd8] udp: port 52955 already in use
21 Jun 16:29:16 - [info] [udp in:bc6a5c5a.dc92b] udp: port 52955 already in use
21 Jun 16:29:16 - [info] [udp in:6d0293d0.7830fc] udp: port 52955 already in use
21 Jun 16:29:16 - [info] [udp in:db213c2c.21a8a] udp: port 52955 already in use
21 Jun 16:29:16 - [info] [udp in:86a1abd2.8da938] udp: port 8890 already in use
21 Jun 16:29:16 - [info] [udp in:91649fa.603c66] udp: port 52955 already in use
21 Jun 16:29:16 - [info] [udp in:679f0974.f22048] udp: port 52955 already in use
21 Jun 16:29:16 - [info] [udp in:834ea885.7a8108] udp: port 52955 already in use
21 Jun 16:29:16 - [info] Started flows
21 Jun 16:29:16 - [info] [udp in:e8fa8d62.5ba14] udp listener at 0.0.0.0:52955
21 Jun 16:29:16 - [info] [udp in:f0a7b791.8fbdd8] udp listener at 0.0.0.0:52955
21 Jun 16:29:16 - [info] [udp in:bc6a5c5a.dc92b] udp listener at 0.0.0.0:52955
21 Jun 16:29:16 - [info] [udp in:6d0293d0.7830fc] udp listener at 0.0.0.0:52955
21 Jun 16:29:16 - [info] [udp in:db213c2c.21a8a] udp listener at 0.0.0.0:52955
21 Jun 16:29:16 - [info] [udp in:91649fa.603c66] udp listener at 0.0.0.0:52955
21 Jun 16:29:16 - [info] [udp in:679f0974.f22048] udp listener at 0.0.0.0:52955
21 Jun 16:29:16 - [info] [udp in:834ea885.7a8108] udp listener at 0.0.0.0:52955
21 Jun 16:29:16 - [info] [udp in:610c4dfa.510b74] udp listener at 0.0.0.0:8890
21 Jun 16:29:16 - [info] [udp in:86a1abd2.8da938] udp listener at 0.0.0.0:8890
21 Jun 16:29:16 - [info] [udp out:eaec231.1a027e] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:29:16 - [info] [udp out:bc7c5bb9.f7ae08] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:29:16 - [info] [udp out:ed91acb.4b6765] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:29:16 - [info] [udp out:bdd1e889.8e4d98] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:29:16 - [info] [udp out:327c07ef.f86218] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:29:16 - [info] [udp out:44d94dbd.d7c874] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:29:16 - [info] [udp out:d256ff94.22cd1] udp re-use socket: 52955 -> 192.168.10.1:8889
21 Jun 16:29:16 - [info] [udp out:9297f027.bc6b] udp re-use socket: 52955 -> 192.168.10.1:8889`

**Comment by johnwalicki** [comment]
The MAC OS X firewall is blocking the telemetry data.  You need to open the firewall for the UDP port.

**Comment by johnwalicki** [comment]
Part 5 of the Node-RED Tello Control repo provides some instructions on how to open up the UDP ports in your firewall.
https://github.com/johnwalicki/Node-RED-Tello-Control/blob/master/docs/PART5.md
